### ISSUE TITLE
Import source failed CURL ERROR:SSL

### ISSUE THREAD

**Issue by Calanon** [nbuchwitz/icingaweb2-module-pve#4]
From what I can see is that because we are not using a certificate curl is unable to validate the SSL cert.  Anyway to bypass this?

## Current Behavior
This Import Source failed when last checked at 2019-04-05 14:33:16: CURL ERROR: SSL certificate problem: unable to get local issuer certificate

**Comment by nbuchwitz** [comment]
Should work if you set both verify options to false.
