### ISSUE TITLE
Documentation on key column is missing

### ISSUE THREAD

**Issue by dynamicat** [nbuchwitz/icingaweb2-module-pve#6]
Hi there,
When I try to add a PVE host I get the following message:

This Import Source failed when last checked at 2019-04-09 17:10:21: No key column "ph-a-10" in row 1

**Comment by nbuchwitz** [comment]
How does your import source config look like? I'd guess that you specified the key column wrong.

**Comment by Calanon** [comment]
You mean the director import source?

**Comment by Calanon** [comment]
So I still get the same error:
This Import Source failed when last checked at 2019-04-10 11:17:51: No key column "ph-a-04" in row 1

This is the table on row 1 of the table import_source:

  | id | source_name | key_column | provider_class | import_state | last_error_message | last_attempt | description
-- | -- | -- | -- | -- | -- | -- | -- | --
 | 1 | ph-a-04 | ph-a-04 | Icinga\Module\Pve\ProvidedHook\Director\ImportSour... | failing |   | 2019-04-10 11:15:36 | NULL

**Comment by nbuchwitz** [comment]
The key column name should be ``name`` as showed in the exampl

**Comment by Calanon** [comment]
Everything has worked correctly.  Many thanks.  Is there any guide on how to use it?

**Comment by nbuchwitz** [comment]
No there isn't any documentation beside from the example, but a PR with some lessons learned is always welcome!

**Comment by nbuchwitz** [comment]
Done in #19
