### ISSUE TITLE
Not able to import VMs

### ISSUE THREAD

**Issue by dynamicat** [nbuchwitz/icingaweb2-module-pve#8]
I have, with your help been able to import source a ve host server.  But when I use the same method for importing VMs I always get the following error:

> This Import Source failed when last checked at 2019-04-12 15:55:38: No key column "name" in row 1

From your guidance you stated I should populate the column_key with the value "name" is this correct?

**Comment by devopstales** [comment]
Add `vm_id` instad of `name`.
